title: Wenhao Blogs
description: My Blogs
author: Wenhao Chen
github: https://github.com/wenhaochen
about: Keep on moving up.
disqus_shortname: stackproblems
avatar_url: /static/img/taksim.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/wenhaochen"

share:

urls:
    - text: About Me
      url: /about/
    - text: CSDN Blog
      url: "https://blog.csdn.net/chenwenhao0304"
    - text: Outlier Analysis
      url: /outlier_analysis/

url: "https://wenhaochen.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
